### PR TITLE
Fix small grammar and wording issues in messages

### PR DESCRIPTION
**Pull request by lbraun**
Hey guys! Thanks for this great app. Thought I'd open a PR for some small grammar issues since you said contributions were welcome. -Lucas

### CODE REVIEW

**Comment by tvlooy** [comment]
Thanks Lucas!

**Comment by tvlooy** [comment]
@lbraun your github profile says you are located in Castelló de la Plana, Spain. If you speak Spanish and are up to it I would welcome additional translations for https://github.com/Intracto/SecretSanta/blob/master/app/Resources/translations/messages.es.yml see everywhere there are # in front of a line these translations are missing. You can look at the english translation file to see what the original text is. What do you think?

**Comment by lbraun** [comment]
Hi @tvlooy, I'm just studying here actually and I'm not a native Spanish speaker, but I'll see if I can't rope one of my Spanish classmates into doing it. Would love to help! @fabianperotti maybe you are interested in this?

**Comment by tvlooy** [comment]
We would be very happy with your help :-)

**Pull request merged**
