### PR TITLE
Multilingual support

### PR DESCRIPTION
**Pull request by hvanoch**
Hi,

Added multilingual support. 
Available locales are requested through the parameters.yml.
Auto creates routes for all the available locales using the locale in the route (/nl/privacy-policy, /fr/privacy-policy, etc) except for the default locale (en) which stays the same

### CODE REVIEW

**Comment by hvanoch** [comment]
Probably still needs some sort of language chooser + auto detection of current locale

**Comment by tvlooy** [comment]
Nice work. We do need hreflang implementation now before this can be merged because of the Google. https://support.google.com/webmasters/answer/189077 can you add this for all translated pages? Translations also still have to happen, can you pass the files to Pieter M. (NL) and Jonathan (FR)? I think @tvmintracto won't mind if they take a little time for this.

**Comment by tvlooy** [comment]
switcher and detection would be nice idd

**Comment by hvanoch** [comment]
Switcher and detection implemented. 
Also the hreflang tags in the head
Switcher could use some extra css styling.

**Comment by tvlooy** [comment]
great! Now the only thing we need is NL/FR copies and this can go live IMO

**Comment by hvanoch** [comment]
@tvlooy 
Could you have an other look. NL en FR languages added + now also using localized dates.

**Comment by tvlooy** [comment]
maybe I'm missing something but the language switcher currently looks a bit lame :-) (no css, no flag or anything)

The rest looks fine. Merging it. If you make any changes to the switcher just push to the main repo.

**Pull request merged**
