### PR TITLE
Upgrade symfony to 3.4

### PR DESCRIPTION
**Pull request by acrobat**
I leave it up to you @tvlooy if you want to merge this now or after the season is over. I think we're pretty covered by the behat tests, but ping me if you want to leave this open and need a rebase.

\+ I've also updated the directory structure to the symfony 3 structure. This will make it easier to update to sf4 and it's specific directory structure. So also check if there are specific scripts (cronjobs etc) which run on the server and use the old `app/console` script instead of the new `bin/console`

### CODE REVIEW

**Comment by tvlooy** [comment]
yeah we're going to wait a few days. No need to rush this one out :-)

**Comment by acrobat** [comment]
Haha good one! Don't let this ruin the presents and turkey 😄

**Comment by tvlooy** [comment]
```
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Could not open input file: app/console
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Could not open input file: app/console
Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception
```

**Comment by acrobat** [comment]
Hmm when do you get this error?

**Comment by tvlooy** [comment]
Jup looks good now. I'm pulling this into master. No deploys today ;-) but will probably deploy on Wednesday.

ps: sfeer https://www.youtube.com/watch?v=vCeWA7vjMdg ;-)

**Comment by acrobat** [comment]
Woohoo! 🎉 Make sure you also check the cronjob config on the server, there could be some `app/console` usages left!

**Comment by tvlooy** [comment]
This one is in production. I replaced app/console with bin/console in the crons

**Comment by acrobat** [comment]
yeah 💪! Let me know if anything is wrong in production!

**Pull request merged**
