### PR TITLE
General insight fixes

### PR DESCRIPTION
**Pull request by acrobat**
- Set a good default value for the secret parameter (only used locally)
- Removed the web/config.php as it is only used to bootstrap a symfony app
- Added the sensiolabs config to the repo, make management easier

@tvlooy maybe it's a good idea to create a sensiolabs insight project for Intracto/SecretSanta (instead of the tvlooy fork), this way each member with admin access to this project will also be able to manage the insights project (ignoring false positives, config, etc)

### CODE REVIEW

**Comment by tvlooy** [comment]
pre_composer_script: |
    #!/bin/bash

    shopt -s dotglob nullglob
    cp app/config/parameters.yml.dist app/config/parameters.yml
    sed -i -e "s/secret:.*/secret: ThisTokenIsS3cr3t/" app/config/parameters.yml

    cp web/robots.txt ./
    rm web/config.php
    sed -i -e "s/plaintext/sha512/" app/config/security.yml
    
    # No warnings on travis files
    rm app/config/router_test_travis.php
    # No warnings on behat stuff
    rm -rf src/Intracto/SecretSantaBundle/Behat
    rm -rf src/Intracto/SecretSantaBundle/Features
    
    # Don't treat SVG files as templates
    cat /dev/null > src/Intracto/SecretSantaBundle/Resources/views/Common/santaSvg.html.twig
    cat /dev/null > src/Intracto/SecretSantaBundle/Resources/views/Common/reindeerSvg.html.twig

**Comment by tvlooy** [comment]
this is the script I use in insight. I think we want some things in git like config.php but remove them in the insight script (and in the deploy). I'll take a look at how to transfer the repo to some place where we can better share access

**Comment by acrobat** [comment]
:+1:

**Comment by tvlooy** [comment]
"Upgrade to a Business plan to be able to share your analyses." :-( Intracto is a group not a user so that won't work either

**Comment by tvlooy** [comment]
but I'm in favour of fixing the insights stupidities in the pre_composer_script and not by trying to fix the project. For me, it's a guideline. Not everything insight reports is noteworthy. Maybe it's a good idea to put a cleanup script in the repo and run that in pre_composer_script instead so it's visible for contributors and you have the ability to work on that part too. What do you think?

**Comment by acrobat** [comment]
Yes indeed, fixing this for the sake of insight result is overkill. But I think we should discuss if we should keep using insights or move to some other service (I've been testing some). Because insights only keeps the last 5 scans (in free edition). Ideally we would enable insights to test each PR for regressions, but with this low retention the 6th open PR would override a previous test result.

I've been testing scrutinizer-ci, codeclimate and codacy but I need some more time to find which one would be more usable. Then we can discuss if we want to continue with insights or move to another service

**Comment by tvlooy** [comment]
Moving to a different tool is very much an option for me because I'm not satisfied with Insights. Nice job, love it.

**Comment by acrobat** [comment]
Closing this PR as we are not going to merge this. I've opened #330 to do some research on the different code quality tools

**Pull request closed without merging**
