### PR TITLE
Convert js files to ts

### LINKED ISSUE #486: Refactor proposal: move from javascript to Typescript
In order to facilitate readability of front-end code, I suggest moving from javascript to Typescript. It would greatly help people understand the code even if they are new.

I can do the setup & rewrite for you if you want.  It would also help me for the feature proposed in #485.

### PR DESCRIPTION
**Pull request by GerkinDev**
Build tooling are configured. Closes #486.

TODO: Set-up [eslint](https://eslint.org/) for coding style constraint in js/ts files. Add unit tests ?

### CODE REVIEW

**Comment by JanDC** [comment]
Great work @GerkinDev! I'll check it out a soon as I can...

**Comment by GerkinDev** [comment]
Now that the source code is in Typescript, I highly suggest a rewrite of some parts of the code to follow eslint recommended lint settings, or custom ones.

For now, if I can suggest some changes, I would personally replace all `var` keywords with `const` or `let`, & use more arrow functions to help making `this` keyword more easily readable, since it can only be redefined in standard functions. Also, some DOM queries are re-ran every time some functions are executed. So selecting them out of the scope of the function would be a bit faster.

There's a lot more that can be done, but I need your feedbacks to know what to do.

Happy new year :clinking_glasses:

**Comment by tvlooy** [comment]
@GerkinDev excuse me for the delay. The problem is that I am not into frontend and I currently don't have a reviewer for this on my side. But I am willing to merge this if you still want to make this change happen and are willing to help fix any fallout that might occur. Please give me a heads up! Thanks!

**Comment by tvlooy** [comment]
No activity

**Comment by GerkinDev** [comment]
Hi,

I'm quite busy right now too. But changes are mostly non-functional, mainly syntax upgrades from JS to TS. So yeah, I guess I could give some minutes to fix (improbable) regressions, but there should be none.

What else would you like ?

**Pull request closed without merging**
