### PR TITLE
Use mandrill as a relay for hotmail etc.

### PR DESCRIPTION
**Pull request by tvlooy**

### CODE REVIEW

**Comment by coudenysj** [comment]
Cool! Has this been deployed yet?

**Comment by tvlooy** [comment]
Yes. We did the same last year. Why? :-)

**Comment by coudenysj** [comment]
I created a new list yesterday around 21:40, everybody got the mails, except the @hotmail addresses :(.

**Comment by tvlooy** [comment]
ah that explains your question :-)
it was deployed during the day so it should have worked at 21:40, maybe just a delay (according to mandrill hotmails is still working at the moment)
some of the hotmail users of your party received the email. Try resending the others. They should have gotten them
I am still talking to hotmail to get a better fix for this so fingers crossed

**Comment by coudenysj** [comment]
Thanks!

**Comment by tvlooy** [comment]
yw!

**Pull request merged**
