### PR TITLE
Temporary fix for #41 - memory issue with reminder e-mails

### PR DESCRIPTION
**Pull request by TomCan**
- limit the number of entries handled at a time, drasticly reduces the
  time and memory the entitymanager needs to process the updates.
- command had a --time-limit option that will make the command stop after
  a number of seconds.

eg. The following command could be used in combination with a crontab set
to run each minute

php app/console intracto:mails:reminders:send --time-limit=50 --force

Entries are processed in batches (default 10, configurable) and a single flush of the spool is done at the end of the batch. Keeping batches small is advised (run more often with smaller batches).

A permanent fix/rewrite of the batch e-mail system is also in the make (enhancement for 2016?).

### CODE REVIEW

**Comment by tvlooy** [comment]
Thanks Tom!

But, before this can be merged, we must first investigate why some people get a mail that "the wishlist is updated" but nothing is in the list (often reported). Or even get the wishlist of someone else (often reported). So must be checked what's going on there.

Apart of that, I'm only merging the really essential things right now. We have 2 weeks to go before this season ends. Let's just do that first ;-)

**Comment by TomCan** [comment]
This is just to fix the current problem we are facing on production. 

I agree on dropping the Wishlist notifications if these are not reliable (that's just a single line that need to be commented out), but are we also dropping the notifications to remind the user to actually look at the entry? I do believe that these are very relevant, definitely in these last few weeks of the season. Other than a simple reminder, it also provides the user with the link to their entry.

**Comment by tvlooy** [comment]
Ah. Agree with that. Can you merge / deploy, enable the cron again and follow up if all goes well? That would help me a lot right now. :-)

**Comment by tvlooy** [comment]
:+1:

**Pull request merged**
