### PR TITLE
forgot manage link

### PR DESCRIPTION
**Pull request by acrobat**
**Still work in progress**

This pr fixes issue #1 

Done:
- [x] Add extra db field to indicate pool admin
- [x] Write query to fix new admin field for existing records
```
UPDATE Entry SET poolAdmin = true WHERE id IN (SELECT sub.admin_entry_id FROM (SELECT
    (SELECT id FROM Entry WHERE poolId = p.id ORDER BY id ASC LIMIT 1) as admin_entry_id FROM Pool p) sub);
```
- [x] Add link to faq
- [x] Finish page to request mail
- [x] Email layout

Todo:
- [ ] Add link to translations other than "en" and "nl"

### CODE REVIEW

**Comment by tvlooy** [comment]
:+1:

**Comment by acrobat** [comment]
@tvlooy Better late than never! PR is ready but should be tested before merge (creation of pools and sending of the mails should work!) After merge the update statement should be run to fix existing entries!

I've added the link to english and dutch faq translations and added the new translation to en and nl

**Comment by tvlooy** [comment]
deployed. Will test and finish this weekend

**Comment by tvlooy** [comment]
Todo
- translation tags worden niet vertaald
- mail verzenden krijgt een error
- in mail best wel zetten wanneer de pool is aangemaakt en of hij bevestigd (uitgestuurd) was of niet

(ben de conversie aan het draaien, gaat precies wel effe duren)

**Pull request merged**
