### PR TITLE
Compress svg images and fix sensiolabs insights warnings

### PR DESCRIPTION
**Pull request by acrobat**
> 6% of all your templates have more than 200 lines

By compressing the svg files this issue will be resolved (I think..)

### CODE REVIEW

**Comment by tvlooy** [comment]
I don't know if we have to try to fix this issue by compressing the SVG. SensiolabsInsight should not treat an SVG as a template. I ignored this file in SensiolabsInsight. I don't know if compressing the SVG has other advantages ...

**Comment by acrobat** [comment]
Ok, we will leave like this for now!

**Comment by tvlooy** [comment]
badass :-)

**Comment by tvlooy** [comment]
and that fixed it ...

**Pull request closed without merging**
