### PR TITLE
Switch gulp to symfony encore

### PR DESCRIPTION
**Pull request by acrobat**
In this PR:

- Removes gulp
- Add symfony encore 
- Recreate the gulp setup in encore
- Removed assetic
- Removes unused js/css files after move to encore/npm setup

The layout looks still ok and all behat tests still pass.

Related to #320

### CODE REVIEW

**Comment by tvlooy** [comment]
ok for me. Can you merge and deploy?

**Comment by acrobat** [comment]
@tvlooy Ok will do! But I don't think I've access to the new server to start the deploy

**Comment by tvlooy** [comment]
your key is on the server so that should work. Make sure you are on master and have the latest code (it takes the code from Github but runs the deploy script that is on your machine) then run "make deploy"

**Comment by acrobat** [comment]
Thanks ssh login works! I will merge and deploy this PR tomorrow!

**Pull request merged**
