### PR TITLE
Header animations

### PR DESCRIPTION
**Pull request by joericlaes**
I've made a lot of changes to the header. I also added Gulp to manage our front-end workflow. This is a rather basic setup, but it does the job.

If you have any questions on some changes, just put a comment on the code line and I"ll look into it. 

Also updated the modernizr library since I use some new css techniques to render the animations. Modernizr checks if these features are enabled or not. If not, the default static background is shown.

### CODE REVIEW

**Comment by tvlooy** [comment]
Can you document the frontend stuff in README.md? Dependencies to install and commands to run ... I also probably need to put them in deploy.sh.

**Comment by joericlaes** [comment]
Hi Tom,

The compiled stylesheets are included in the repo. I will update the readme.

**Comment by tvlooy** [comment]
@joericlaes deployed! ps: what browsers did you test? Seeing some weird (non blocking) things in Linux / Firefox but that combo has given me weird things a lot of times.

Oh, and does this fix Pieter's lang switcher problem too?

**Comment by tvlooy** [comment]
@joericlaes language switcher seems totally broken and there are 404's, ... hmz, seems like we broke some stuff

**Comment by tvlooy** [comment]
dat laatste is gefixed. Images die 404's veroorzaken staan in comment en language switcher werkt terug. Header click zat om een of andere reden plots in de weg.

**Comment by joericlaes** [comment]
@tvlooy IE11, Chrome, FF, Safari op osx en Windows geven hier geen issues.

**Comment by tvlooy** [comment]
@joericlaes 'k heb het ook enkel op Linux / Firefox en enkel app_dev dus zal wel ok zijn. Voorbeeld in bijlage:
optimised

**Pull request merged**
