### PR TITLE
sf 2.8 testing

### PR DESCRIPTION
**Pull request by rvanginneken**
;)

### CODE REVIEW

**Comment by tvlooy** [comment]
tumblr_inline_njswwdlkqg1r9ujyl

**Comment by acrobat** [comment]
https://i.imgflip.com/tr10a.jpg :D

**Comment by acrobat** [comment]
meme

**Comment by rvanginneken** [comment]
Yep, and it worked :D
Had je er nochtans over gemailed @tvlooy

**Comment by tvlooy** [comment]
tumblr_inline_njswwdlkqg1r9ujyl

**Pull request closed without merging**
